spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lojaonneo@gmail.com
    password: 'azbr xfgi kjlo zvte'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  thymeleaf:
    enable: true

envio:
  email:
    remetente: lojaonneo@gmail.com
    nomeRemetente: 'Javanauta'

server:
  port: 8089